const C=window.LUNHS_CONFIG, sb=window.supabase.createClient(C.url,C.key); let me=null;
function normalizeSchoolId(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9._-]/g,'-')}
function internalEmail(id){return normalizeSchoolId(id)+'@accounts.lunhs.local'}
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active');if(id==='announcements')loadPublicPosts();scrollTo(0,0)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b)show(b.dataset.view);let t=e.target.closest('[data-tab]');if(t){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderAdminTab(t.dataset.tab)}})
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Signing in…';let {data,error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#loginMsg').className='error';$('#loginMsg').textContent=error.message;return}await openDashboard(data.user)};
async function profile(uid){return await sb.from('profiles').select('*').eq('id',uid).single()}
async function openDashboard(u){let {data:p,error}=await profile(u.id);if(error||!p){$('#loginMsg').className='error';$('#loginMsg').textContent='Signed in, but profile could not be read: '+(error?.message||'not found');return}me=p;$('#loginNav').hidden=true;$('#dashNav').hidden=false;$('#logout').hidden=false;$('#welcome').textContent='Welcome, '+p.display_name;$('#identity').textContent=`${p.role.toUpperCase()} • ${p.school_id||''}`;if(p.role==='admin')renderAdmin();if(p.role==='teacher')renderTeacher();if(p.role==='student')renderStudent();show('dashboard')}
async function loadPublicPosts(){let {data,error}=await sb.from('posts').select('*').eq('published',true).order('created_at',{ascending:false});$('#publicPosts').innerHTML=error?`<p class=error>${esc(error.message)}</p>`:(data?.length?data.map(p=>`<article class=post><small>${esc(p.type)}</small><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p></article>`).join(''):'<article>No announcements yet.</article>')}
function renderAdmin(){$('#dashboardBody').innerHTML=`<div class=tabs><button class="tab active" data-tab=overview>Overview</button><button class=tab data-tab=posts>Announcements</button><button class=tab data-tab=subjects>Subjects</button><button class=tab data-tab=profiles>Users</button><button class=tab data-tab=assignments>Assignments</button><button class=tab data-tab=grades>Grades</button></div><div id=adminContent></div>`;renderAdminTab('overview')}
async function renderAdminTab(tab){let box=$('#adminContent');if(!box)return;box.innerHTML='Loading…';
if(tab==='overview'){let [p,s,g,po]=await Promise.all([sb.from('profiles').select('id',{count:'exact',head:true}),sb.from('subjects').select('id',{count:'exact',head:true}),sb.from('grades').select('id',{count:'exact',head:true}),sb.from('posts').select('id',{count:'exact',head:true})]);box.innerHTML=`<div class=stats><div class=stat><b>${p.count??0}</b><p>Profiles</p></div><div class=stat><b>${s.count??0}</b><p>Subjects</p></div><div class=stat><b>${g.count??0}</b><p>Grade Records</p></div><div class=stat><b>${po.count??0}</b><p>Posts</p></div></div><div class=notice>Auth accounts are created securely in Supabase Authentication. This browser portal never uses a secret/service-role key.</div>`}
if(tab==='posts'){let {data}=await sb.from('posts').select('*').order('created_at',{ascending:false});box.innerHTML=`<div class=panel><h2>New Announcement / Event</h2><form id=postForm><div class=formgrid><label>Type<select id=ptype><option>Announcement</option><option>Event</option></select></label><label>Title<input id=ptitle required></label></div><label>Details<textarea id=pbody></textarea></label><button class=primary>Publish</button><span id=pmsg></span></form></div><div class=tablewrap><table class=data><tr><th>Type</th><th>Title</th><th>Date</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.title)}</td><td>${new Date(x.created_at).toLocaleDateString()}</td></tr>`).join('')}</table></div>`;$('#postForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.from('posts').insert({type:$('#ptype').value,title:$('#ptitle').value,body:$('#pbody').value,published:true,author_id:me.id});$('#pmsg').textContent=error?error.message:' Published!';if(!error)renderAdminTab('posts')}}
if(tab==='subjects'){let {data}=await sb.from('subjects').select('*').order('grade_level').order('name');box.innerHTML=`<div class=panel><h2>Add Subject</h2><form id=subForm class=formgrid><label>Subject<input id=sname required></label><label>Grade Level<input id=sgrade placeholder="8"></label><label>&nbsp;<button class=primary>Add Subject</button></label></form><p id=smsg></p></div><div class=tablewrap><table class=data><tr><th>Subject</th><th>Grade Level</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.grade_level)}</td></tr>`).join('')}</table></div>`;$('#subForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.from('subjects').insert({name:$('#sname').value,grade_level:$('#sgrade').value});$('#smsg').textContent=error?error.message:'Subject added.';if(!error)renderAdminTab('subjects')}}
if(tab==='profiles'){let {data,error}=await sb.from('profiles').select('display_name,school_id,role,grade_level,section').order('display_name');box.innerHTML=`<div class=panel><h2>Create Student / Teacher Account</h2><form id=userForm><div class=formgrid><label>Role<select id=urole><option value=student>Student</option><option value=teacher>Teacher</option></select></label><label>Full Name<input id=uname required></label><label>School ID / LRN<input id=usid required></label><label>Email<input id=uemail type=email required></label><label>Temporary Password<input id=upass type=password minlength=8 required></label><label>Grade Level<input id=ugrade placeholder="8"></label><label>Section<input id=usection placeholder="Section name"></label></div><button class=primary>Create Account</button><p id=umsg></p></form></div><div class=tablewrap><table class=data><tr><th>Name</th><th>ID</th><th>Role</th><th>Grade</th><th>Section</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.display_name)}</td><td>${esc(x.school_id)}</td><td>${esc(x.role)}</td><td>${esc(x.grade_level)}</td><td>${esc(x.section)}</td></tr>`).join('')}</table></div>${error?`<p class=error>${esc(error.message)}</p>`:''}`;$('#userForm').onsubmit=async e=>{e.preventDefault();let m=$('#umsg');m.className='';m.textContent='Creating account…';const payload={role:$('#urole').value,display_name:$('#uname').value.trim(),school_id:$('#usid').value.trim(),email:internalEmail($('#usid').value.trim()),password:$('#upass').value,grade_level:$('#ugrade').value.trim()||null,section:$('#usection').value.trim()||null};
let {data:r,error:fnError}=await sb.functions.invoke('create-school-user',{body:payload});
if(fnError){
  let detail=fnError.message||'Account creation failed.';
  try{if(fnError.context&&typeof fnError.context.json==='function'){let body=await fnError.context.json();detail=body.error||body.message||detail}}catch(_){}
  m.className='error';m.textContent=detail;return
}
if(!r?.ok){m.className='error';m.textContent=r?.error||'Account creation failed.';return}
m.className='ok';m.textContent=r.message||'Account and LUNHS profile created successfully.';
setTimeout(()=>renderAdminTab('profiles'),700)}}
if(tab==='assignments'){let [a,t,s]=await Promise.all([sb.from('teacher_assignments').select('id,section,teacher_id,subjects(name)'),sb.from('profiles').select('id,display_name,school_id').eq('role','teacher').order('display_name'),sb.from('subjects').select('id,name,grade_level').order('name')]);box.innerHTML=`<div class=panel><h2>Assign Teacher</h2><form id=assignForm class=formgrid><label>Teacher<select id=ateacher required><option value="">Select teacher</option>${(t.data||[]).map(x=>`<option value="${x.id}">${esc(x.display_name)} (${esc(x.school_id)})</option>`).join('')}</select></label><label>Subject<select id=asubject required><option value="">Select subject</option>${(s.data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}${x.grade_level?' - Grade '+esc(x.grade_level):''}</option>`).join('')}</select></label><label>Section<input id=asection required></label><label>&nbsp;<button class=primary>Assign</button></label></form><p id=amsg></p></div><div class=tablewrap><table class=data><tr><th>Teacher UUID</th><th>Subject</th><th>Section</th></tr>${(a.data||[]).map(x=>`<tr><td>${esc(x.teacher_id)}</td><td>${esc(x.subjects?.name)}</td><td>${esc(x.section)}</td></tr>`).join('')}</table></div>`;$('#assignForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.from('teacher_assignments').insert({teacher_id:$('#ateacher').value,subject_id:Number($('#asubject').value),section:$('#asection').value.trim()});$('#amsg').textContent=error?error.message:'Teacher assigned.';if(!error)renderAdminTab('assignments')}}
if(tab==='grades'){let {data,error}=await sb.from('grades').select('school_year,section,q1,q2,q3,q4,subjects(name),student_id').limit(100);box.innerHTML=`<div class=tablewrap><table class=data><tr><th>Student UUID</th><th>Subject</th><th>Section</th><th>Q1</th><th>Q2</th><th>Q3</th><th>Q4</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.student_id)}</td><td>${esc(x.subjects?.name)}</td><td>${esc(x.section)}</td><td>${x.q1??'-'}</td><td>${x.q2??'-'}</td><td>${x.q3??'-'}</td><td>${x.q4??'-'}</td></tr>`).join('')}</table></div>${error?`<p class=error>${esc(error.message)}</p>`:''}`}
}
async function renderStudent(){let {data,error}=await sb.from('grades').select('q1,q2,q3,q4,school_year,subjects(name)').eq('student_id',me.id);$('#dashboardBody').innerHTML=`<div class=panel><h2>My Grades</h2>${error?`<p class=error>${esc(error.message)}</p>`:`<div class=tablewrap><table class=data><tr><th>Subject</th><th>Q1</th><th>Q2</th><th>Q3</th><th>Q4</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.subjects?.name)}</td><td>${x.q1??'-'}</td><td>${x.q2??'-'}</td><td>${x.q3??'-'}</td><td>${x.q4??'-'}</td></tr>`).join('')}</table></div>`}</div>`}
async function renderTeacher(){
 let {data,error}=await sb.from('teacher_assignments').select('id,section,subject_id,subjects(name)').eq('teacher_id',me.id);
 $('#dashboardBody').innerHTML=`<div class=panel><h2>My Teaching Assignments</h2>${error?`<p class=error>${esc(error.message)}</p>`:`<label>Select Class<select id=tclass><option value="">Choose subject / section</option>${(data||[]).map(x=>`<option value="${x.subject_id}|${esc(x.section)}">${esc(x.subjects?.name)} — ${esc(x.section)}</option>`).join('')}</select></label><div id=gradeArea></div>`}</div>`;
 if($('#tclass'))$('#tclass').onchange=loadTeacherClass;
}
async function loadTeacherClass(){
 let v=$('#tclass').value;if(!v){$('#gradeArea').innerHTML='';return} let [sid,section]=v.split('|');
 let {data:students,error}=await sb.from('profiles').select('id,display_name,school_id').eq('role','student').eq('section',section).order('display_name');
 if(error){$('#gradeArea').innerHTML=`<p class=error>${esc(error.message)}</p>`;return}
 let gm={}; if(students?.length){let {data:g}=await sb.from('grades').select('*').eq('subject_id',Number(sid)).in('student_id',students.map(x=>x.id));(g||[]).forEach(x=>gm[x.student_id]=x)}
 $('#gradeArea').innerHTML=`<h3>Class List — ${esc(section)}</h3><p class=notice>Enter 60–100. Leave a quarter blank if not yet available.</p><div class=tablewrap><table class=data><tr><th>Student</th><th>ID/LRN</th><th>Q1</th><th>Q2</th><th>Q3</th><th>Q4</th><th></th></tr>${(students||[]).map(s=>{let g=gm[s.id]||{};return `<tr data-student="${s.id}"><td>${esc(s.display_name)}</td><td>${esc(s.school_id)}</td>${['q1','q2','q3','q4'].map(q=>`<td><input class="${q}" type=number min=60 max=100 step=.01 value="${g[q]??''}"></td>`).join('')}<td><button class=primary data-savegrade="${s.id}">Save</button></td></tr>`}).join('')}</table></div>${students?.length?'':'<p>No students found in this section.</p>'}`;
 document.querySelectorAll('[data-savegrade]').forEach(b=>b.onclick=()=>saveGrade(b.dataset.savegrade,Number(sid),section));
}
async function saveGrade(studentId,subjectId,section){
 let row=document.querySelector(`tr[data-student="${studentId}"]`),v={};
 for(let q of ['q1','q2','q3','q4']){let x=row.querySelector('.'+q).value;v[q]=x===''?null:Number(x);if(v[q]!==null&&(v[q]<60||v[q]>100)){alert('Grades must be from 60 to 100.');return}}
 let {error}=await sb.from('grades').upsert({student_id:studentId,subject_id:subjectId,teacher_id:me.id,section,school_year:'2026-2027',...v},{onConflict:'student_id,subject_id,school_year'});
 alert(error?'Could not save: '+error.message:'Grade saved successfully.');
}
(async()=>{let {data:{session}}=await sb.auth.getSession();if(session?.user)await openDashboard(session.user)})();