create table if not exists public.site_sections(
 id bigint generated by default as identity primary key,
 section_key text unique not null, page_name text not null,
 title text not null default '', body text not null default '',
 updated_by uuid references public.profiles(id), updated_at timestamptz default now()
);
alter table public.site_sections enable row level security;
drop policy if exists "public read site sections" on public.site_sections;
create policy "public read site sections" on public.site_sections for select to anon,authenticated using(true);
drop policy if exists "admin insert site sections" on public.site_sections;
create policy "admin insert site sections" on public.site_sections for insert to authenticated with check(public.current_user_role()='admin' and updated_by=auth.uid());
drop policy if exists "admin update site sections" on public.site_sections;
create policy "admin update site sections" on public.site_sections for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');
drop policy if exists "admin delete site sections" on public.site_sections;
create policy "admin delete site sections" on public.site_sections for delete to authenticated using(public.current_user_role()='admin');
grant select on public.site_sections to anon,authenticated;
grant insert,update,delete on public.site_sections to authenticated;
grant usage,select on all sequences in schema public to authenticated;
insert into public.site_sections(section_key,page_name,title,body) values
('home_welcome','Home','Welcome to LUNHS','A school community where learners are encouraged to discover, participate, create, and succeed.'),
('about_main','About','Our School','Learn more about La Union National High School and our school community.'),
('academics_main','Academics','Academics','Explore academic programs, learning areas, laboratories, and learner support.'),
('downloads_main','Downloads','Downloads','Official school forms, resources, publications, and downloadable files.'),
('contact_main','Contact','Contact Us','Connect with La Union National High School for official inquiries.')
on conflict(section_key) do nothing;
