
-- LUNHS Portal v31 School Information System upgrade
-- Run ONCE in Supabase SQL Editor.

alter table public.posts add column if not exists facebook_url text;
alter table public.posts add column if not exists category text;
alter table public.posts add column if not exists media_type text;
alter table public.posts add column if not exists media_url text;
alter table public.posts add column if not exists thumbnail_url text;

create table if not exists public.school_events(
 id bigint generated by default as identity primary key,title text not null,event_date date not null,
 location text,description text,created_at timestamptz default now());
create table if not exists public.school_resources(
 id bigint generated by default as identity primary key,title text not null,description text,url text not null,created_at timestamptz default now());
create table if not exists public.achievements(
 id bigint generated by default as identity primary key,title text not null,description text,achievement_date date,image_url text,created_at timestamptz default now());
create table if not exists public.facilities(
 id bigint generated by default as identity primary key,name text not null,description text,image_url text,created_at timestamptz default now());
create table if not exists public.emergency_banner(
 id int primary key default 1,message text not null default '',active boolean default false,updated_at timestamptz default now());

alter table public.school_events enable row level security;
alter table public.school_resources enable row level security;
alter table public.achievements enable row level security;
alter table public.facilities enable row level security;
alter table public.emergency_banner enable row level security;

drop policy if exists "public read events" on public.school_events;
create policy "public read events" on public.school_events for select to public using(true);
drop policy if exists "admin events" on public.school_events;
create policy "admin events" on public.school_events for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

drop policy if exists "public read resources" on public.school_resources;
create policy "public read resources" on public.school_resources for select to public using(true);
drop policy if exists "admin resources" on public.school_resources;
create policy "admin resources" on public.school_resources for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

drop policy if exists "public read achievements" on public.achievements;
create policy "public read achievements" on public.achievements for select to public using(true);
drop policy if exists "admin achievements" on public.achievements;
create policy "admin achievements" on public.achievements for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

drop policy if exists "public read facilities" on public.facilities;
create policy "public read facilities" on public.facilities for select to public using(true);
drop policy if exists "admin facilities" on public.facilities;
create policy "admin facilities" on public.facilities for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

drop policy if exists "public read emergency" on public.emergency_banner;
create policy "public read emergency" on public.emergency_banner for select to public using(true);
drop policy if exists "admin emergency" on public.emergency_banner;
create policy "admin emergency" on public.emergency_banner for all to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');

grant select on public.school_events,public.school_resources,public.achievements,public.facilities,public.emergency_banner to anon,authenticated;
grant insert,update,delete on public.school_events,public.school_resources,public.achievements,public.facilities,public.emergency_banner to authenticated;
grant usage,select on all sequences in schema public to authenticated;
notify pgrst,'reload schema';
